export const EVENTS = [
  {
    id: '0',
    slug: 'vice-party',
    name: 'Vice Party',
    venue: 'Balmoral Convention Centre',
    address: 'Victoria Island, Lagos',
    date: '2026-05-31',
    time: '21:00',
    price: null,
    type: 'Rave',
    genre: 'Afrobeats',
    description: 'Lagos biggest party experience. Hosted by Yhemolee. An unforgettable night of music, vibes and premium entertainment.',
    image: 'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479773/Vice_Party_zcjdl4.jpg',
    images: [
      'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479773/Vice_Party_zcjdl4.jpg',
      'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479808/Vice_Party_2_hjbppr.jpg',
      'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479838/Vice_Party_3_qkpsex.jpg',
    ],
    video: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479721/Vice_Party_Video_sg2eno.mp4',
  },
  {
    id: '1',
    slug: 'mainland-block-party',
    name: 'Mainland Block Party',
    venue: 'Mainland Lagos',
    address: 'Lagos Mainland',
    date: '2026-06-14',
    time: '16:00',
    price: 5000,
    type: 'Rave',
    genre: 'Afrobeats/House',
    description: 'The biggest block party on the mainland. Good music, good people, unmatched energy.',
    image: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479578/mainland-block-party_koizdy.mp4',
    video: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479578/mainland-block-party_koizdy.mp4',
  },
  {
    id: '2',
    slug: 'group-therapy',
    name: 'Group Therapy',
    venue: 'Lekki Auditorium',
    address: 'Lekki, Lagos',
    date: '2026-06-20',
    time: '22:00',
    price: 8000,
    type: 'Rave',
    genre: 'Afro-House/Deep House',
    description: 'Lagos most talked about underground rave. No tables, no hierarchy - just pure music and energy.',
    image: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479528/group-therapy_tg2uxw.mp4',
    video: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479528/group-therapy_tg2uxw.mp4',
  },
  {
    id: '3',
    slug: 'element-house',
    name: 'Element House',
    venue: 'Spektrum Hub',
    address: 'Lagos',
    date: '2026-06-27',
    time: '21:00',
    price: 6000,
    type: 'Rave',
    genre: 'Tech-House/Afro-House',
    description: 'Monthly underground rave by Spektrum Entertainment. Heavy audiovisual setups, tech-house and afro-house blends.',
    image: 'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479476/element-house_cimy8n.jpg',
    images: [
      'https://res.cloudinary.com/dvhb8peji/image/upload/v1781479476/element-house_cimy8n.jpg',
    ],
    video: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479429/element-house_sp7aca.mp4',
  },
  {
    id: '4',
    slug: 'purple',
    name: 'Purple',
    venue: 'Lagos',
    address: 'Victoria Island, Lagos',
    date: '2026-07-04',
    time: '22:00',
    price: 10000,
    type: 'Rave',
    genre: 'Afrobeats/House',
    description: 'An exclusive purple-themed rave experience. Premium vibes, curated sounds and an unforgettable atmosphere.',
    image: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479668/purple_wn32yh.mp4',
    video: 'https://res.cloudinary.com/dvhb8peji/video/upload/q_auto,f_auto/v1781479668/purple_wn32yh.mp4',
  },
  {
    id: '5',
    slug: 'inner-circle',
    name: 'Inner Circle Lunar Edition',
    venue: 'Trib3 Lagos',
    address: 'Victoria Island, Lagos',
    date: '2026-02-20',
    time: '18:00',
    price: null,
    type: 'Rave',
    genre: 'Afrobeats/House',
    description: 'RSVP & Invites only. Exclusive lunar edition rave.',
    image: '/events/inner-circle.jpeg',
  },
  {
    id: '6',
    slug: 'rooftop-mix',
    name: 'Rooftop Mix',
    venue: '99 Ajose Adeogun',
    address: 'Victoria Island, Lagos',
    date: '2026-02-21',
    time: '19:00',
    price: null,
    type: 'Rave',
    genre: 'House',
    description: 'Mercury Sound System. RSVP.',
    image: '/events/rooftop-mix.jpeg',
  },
  {
    id: '7',
    slug: 'laid-back',
    name: 'Laid Back - Valentine After Party',
    venue: 'The Vault Social House',
    address: 'Lagos',
    date: '2026-02-21',
    time: '21:00',
    price: 7000,
    type: 'Rave',
    genre: 'Afrobeats',
    description: 'Night to celebrate love. Theme: All Black.',
    image: '/events/laid-back.jpeg',
  },
  {
    id: '8',
    slug: 'good-picnic',
    name: 'The Good Picnic',
    venue: 'Lekki Phase 1',
    address: 'Lekki Phase 1, Lagos',
    date: '2026-02-21',
    time: '15:00',
    price: 15000,
    type: 'Festival',
    genre: 'Afrobeats',
    description: 'Games, music, food, drinks featuring guest DJ Neptune.',
    image: '/events/good-picnic.jpeg',
  },
  {
    id: '9',
    slug: 'trivia-night',
    name: 'Lagos Trivia Night',
    venue: 'Praia',
    address: 'Victoria Island, Lagos',
    date: '2026-02-22',
    time: '17:00',
    price: null,
    type: 'Quiz',
    genre: 'Afrobeat',
    description: 'RSVP. Quiz night with prizes.',
    image: '/events/trivia-night.jpeg',
  },
  {
    id: '10',
    slug: 'friendship-sunday',
    name: 'Friendship Sunday',
    venue: 'Esporta Lounge',
    address: 'No.15 Adekunle Fajuyi Way, Ikeja GRA',
    date: '2026-02-22',
    time: '13:00',
    price: 15000,
    type: 'Sip n Paint',
    genre: 'Afrobeats',
    description: 'Unlimited cocktails, comedy, pottery, painting.',
    image: '/events/friendship-sunday.jpeg',
  },
]