export const EVENTS = [
  {
    id: '1',
    slug: 'inner-circle',
    name: 'Inner Circle Lunar Edition',
    venue: 'Trib3 Lagos',
    address: 'Victoria Island, Lagos',
    date: '2026-02-20',
    time: '18:00',
    price: null,
    type: 'Rave',
    genre: 'Afrobeat/House',
    description: 'RSVP & Invites only. Exclusive lunar edition rave.',
    image: '/events/inner-circle.jpeg'
  },
  {
    id: '2',
    slug: 'karaoke-game',
    name: 'Karaoke & Game Night',
    venue: 'Gameland',
    address: 'The Lekki Coliseum, Lagos',
    date: '2026-02-20',
    time: '18:00',
    price: 5000,
    type: 'Karaoke & Games',
    genre: 'All',
    description: 'More laughs, games, songs and vibes.',
    image: '/events/karaoke-game.jpeg'
  },
  {
    id: '3',
    slug: 'good-picnic',
    name: 'The Good Picnic',
    venue: 'Lekki Phase 1',
    address: 'Lekki Phase 1, Lagos',
    date: '2026-02-21',
    time: '15:00',
    price: 15000,
    type: 'Festival',
    genre: 'Afrobeats',
    description: 'Games, music, food, drinks featuring guest DJ.',
    image: '/events/good-picnic.jpeg'
  },
  {
    id: '4',
    slug: 'singles-breef',
    name: 'Let The Singles Breef!',
    venue: 'Ndubuisi Kanu Park',
    address: 'Ikeja, Lagos',
    date: '2026-02-21',
    time: '15:00',
    price: 6000,
    type: 'Festival',
    genre: 'All',
    description: 'Games, food, music. One day for them, every day for us.',
    image: '/events/singles-breef.jpeg'
  },
  {
    id: '5',
    slug: 'trivia-night',
    name: 'Lagos Trivia Night',
    venue: 'Praia',
    address: 'Victoria Island, Lagos',
    date: '2026-02-21',
    time: '17:00',
    price: null,
    type: 'Quiz',
    genre: 'Afrobeat',
    description: 'RSVP. Quiz night with prizes.',
    image: '/events/trivia-night.jpeg'
  },
  {
    id: '6',
    slug: 'femme-flow',
    name: 'Femme, Flow + Brunch',
    venue: 'HER Mobility',
    address: 'Ikeja GRA, Lagos',
    date: '2026-02-21',
    time: '09:30',
    price: null,
    type: 'Dance & Flow',
    genre: 'All',
    description: 'Women movement experience: mobility flow, heels dancing, health check, brunch.',
    image: '/events/femme-flow.jpeg'
  },
  {
    id: '7',
    slug: 'supper-club',
    name: 'The Supper Club',
    venue: 'Undisclosed',
    address: 'Lagos',
    date: '2026-02-21',
    time: '18:00',
    price: 188000,
    type: 'Dinner',
    genre: 'N/A',
    description: 'Valentine special. ₦188k/couple. RSVP only.',
    image: '/events/supper-club.jpeg'
  },
  {
    id: '8',
    slug: 'laid-back',
    name: 'Laid Back - Valentine After Party',
    venue: 'The Vault Social House',
    address: 'Lagos',
    date: '2026-02-21',
    time: '21:00',
    price: 7000,
    type: 'Rave',
    genre: 'Afrobeats',
    description: 'Night to celebrate love. Theme: All Black.',
    image: '/events/laid-back.jpeg'
  },
  {
    id: '9',
    slug: 'rooftop-mix',
    name: 'Rooftop Mix',
    venue: '99 Ajose Adeogun',
    address: 'Victoria Island, Lagos',
    date: '2026-02-21',
    time: '19:00',
    price: null,
    type: 'Rave',
    genre: 'House',
    description: 'Mercury Sound System. RSVP.',
    image: '/events/rooftop-mix.jpeg'
  },
  {
    id: '10',
    slug: 'friendship-sunday',
    name: 'Friendship Sunday',
    venue: 'Esporta Lounge',
    address: 'No.15 Adekunle Fajuyi Way, Ikeja GRA',
    date: '2026-02-22',
    time: '13:00',
    price: 15000,
    type: 'Sip n Paint',
    genre: 'Afrobeats',
    description: 'Unlimited cocktails, comedy, pottery, painting.',
    image: '/events/friendship-sunday.jpeg'
  },
  {
    id: '11',
    slug: 'macrame',
    name: 'Mindful Macramé',
    venue: 'Breather Studio',
    address: 'Ikoyi, Lagos',
    date: '2026-02-22',
    time: '13:00',
    price: 30000,
    type: 'Creative',
    genre: 'All',
    description: 'Slow creative experience rooted in calm.',
    image: '/events/macrame.jpeg'
  }
]
