export const VENUES = [
  {
    id: '1',
    slug: 'bayrock',
    name: 'Bayrock',
    type: 'Nightclub',
    description: 'Where the real party people gather. Premium nightlife experience. Lagos most exclusive club.',
    address: 'Victoria Island, Lagos',
    cover: '/events/bayrock.jpeg',
    video: null,
    logo: '/events/bayrock.jpeg',
    followers: 22100,
    instagram: '@bayrock.ng',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 10, price: 600000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 10, price: 600000, available: true },
      { id: 't3', section: 'VIP', number: 3, capacity: 8, price: 500000, available: false },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 300000, available: true },
      { id: 't5', section: 'Regular', number: 5, capacity: 6, price: 300000, available: true },
      { id: 't6', section: 'Regular', number: 6, capacity: 4, price: 250000, available: true },
    ]
  },
  {
    id: '2',
    slug: 'quilox',
    name: 'Quilox',
    type: 'Nightclub',
    description: 'Lagos premier nightclub. Luxury experience with top-tier music and ambiance.',
    address: 'Victoria Island, Lagos',
    cover: '/events/quilox.mp4',
    video: '/events/quilox.mp4',
    logo: '/events/quilox.mp4',
    followers: 45200,
    instagram: '@quiloxlagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 8, price: 500000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 8, price: 500000, available: false },
      { id: 't3', section: 'VIP', number: 3, capacity: 6, price: 400000, available: true },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 250000, available: true },
      { id: 't5', section: 'Regular', number: 5, capacity: 6, price: 250000, available: true },
      { id: 't6', section: 'Regular', number: 6, capacity: 4, price: 200000, available: false },
      { id: 't7', section: 'Balcony', number: 7, capacity: 4, price: 150000, available: true },
      { id: 't8', section: 'Balcony', number: 8, capacity: 4, price: 150000, available: true },
    ]
  },
  {
    id: '3',
    slug: 'proxy',
    name: 'Proxy',
    type: 'Nightclub',
    description: 'Underground meets luxury. Proxy is where Lagos creatives and nightlife lovers collide.',
    address: 'Lekki, Lagos',
    cover: '/events/proxy.jpeg',
    video: null,
    logo: '/events/proxy.jpeg',
    followers: 14300,
    instagram: '@proxy_lagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 8, price: 400000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 8, price: 400000, available: false },
      { id: 't3', section: 'Regular', number: 3, capacity: 6, price: 220000, available: true },
      { id: 't4', section: 'Regular', number: 4, capacity: 4, price: 180000, available: true },
    ]
  },
  {
    id: '4',
    slug: 'club-dna',
    name: 'Club DNA',
    type: 'Nightclub',
    description: 'Born different. Club DNA brings a unique energy to Lagos nightlife with cutting edge sound and design.',
    address: 'Lagos',
    cover: '/events/club-dna.jpeg',
    video: null,
    logo: '/events/club-dna.jpeg',
    followers: 11200,
    instagram: '@clubdna_lagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 10, price: 450000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 8, price: 400000, available: true },
      { id: 't3', section: 'Regular', number: 3, capacity: 6, price: 230000, available: false },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 230000, available: true },
      { id: 't5', section: 'Balcony', number: 5, capacity: 4, price: 160000, available: true },
    ]
  },
  {
    id: '5',
    slug: 'secret-palace',
    name: 'Secret Palace',
    type: 'Nightclub',
    description: 'The best kept secret in Lagos. Exclusive access, premium experience, unforgettable nights.',
    address: 'Victoria Island, Lagos',
    cover: '/events/secret-palace.jpeg',
    video: null,
    logo: '/events/secret-palace.jpeg',
    followers: 9800,
    instagram: '@secretpalacelagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 10, price: 600000, available: false },
      { id: 't2', section: 'VIP', number: 2, capacity: 8, price: 550000, available: true },
      { id: 't3', section: 'VIP', number: 3, capacity: 8, price: 550000, available: true },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 300000, available: true },
      { id: 't5', section: 'Regular', number: 5, capacity: 4, price: 250000, available: true },
    ]
  },
  {
    id: '6',
    slug: 'de-chandelier',
    name: 'De Chandelier',
    type: 'Nightclub',
    description: 'Elegance meets energy. De Chandelier is Lagos most glamorous nightclub experience.',
    address: 'Lagos',
    cover: '/events/de-chandelier.jpeg',
    detail: '/events/de-chandelier-1.jpeg',
    images: [
      '/events/de-chandelier.jpeg',
      '/events/de-chandelier-1.jpeg',
    ],
    video: null,
    logo: '/events/de-chandelier.jpeg',
    followers: 16500,
    instagram: '@dechandelier_lagos',
    tables: [
      { id: 't1', section: 'Diamond VIP', number: 1, capacity: 12, price: 800000, available: true },
      { id: 't2', section: 'Diamond VIP', number: 2, capacity: 10, price: 700000, available: false },
      { id: 't3', section: 'VIP', number: 3, capacity: 8, price: 500000, available: true },
      { id: 't4', section: 'VIP', number: 4, capacity: 8, price: 500000, available: true },
      { id: 't5', section: 'Regular', number: 5, capacity: 6, price: 300000, available: true },
    ]
  },
  {
    id: '7',
    slug: 'silver-fox',
    name: 'Silver Fox',
    type: 'Nightclub',
    description: 'Sophisticated and sleek. Silver Fox brings premium nightlife to Lagos with style.',
    address: 'Lagos',
    cover: '/events/silver-fox.jpeg',
    video: null,
    logo: '/events/silver-fox.jpeg',
    followers: 13400,
    instagram: '@silverfoxlagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 10, price: 500000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 8, price: 450000, available: true },
      { id: 't3', section: 'Regular', number: 3, capacity: 6, price: 250000, available: false },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 250000, available: true },
      { id: 't5', section: 'Balcony', number: 5, capacity: 4, price: 180000, available: true },
    ]
  },
  {
    id: '8',
    slug: 'zaza',
    name: 'Zaza',
    type: 'Nightclub',
    description: 'Bold, electric and unapologetic. Zaza is the new face of Lagos nightlife.',
    address: 'Lagos',
    cover: '/events/zaza.jpeg',
    detail: '/events/zaza-1.jpeg',
    images: [
      '/events/zaza.jpeg',
      '/events/zaza-1.jpeg',
    ],
    video: null,
    logo: '/events/zaza.jpeg',
    followers: 19200,
    instagram: '@zazalagos',
    tables: [
      { id: 't1', section: 'VIP', number: 1, capacity: 12, price: 700000, available: true },
      { id: 't2', section: 'VIP', number: 2, capacity: 10, price: 600000, available: false },
      { id: 't3', section: 'VIP', number: 3, capacity: 8, price: 550000, available: true },
      { id: 't4', section: 'Regular', number: 4, capacity: 6, price: 300000, available: true },
      { id: 't5', section: 'Regular', number: 5, capacity: 6, price: 300000, available: true },
    ]
  },
]